### ISSUE TITLE
[BUG] Cannot Select A Range of Chapters Among the Listing

### ISSUE THREAD

**Issue by loriette-01** [maoserr/epublifier#187]
**[EDIT: It seems like someone else has already reported these two bugs ahah, I apologise for the repeat.]**

**Describe the bug**
Hello! I'm a new user and would like to report a couple bugs I noticed (the second one will be opened in another issue to avoid confusion :D)~

When I open the extension Epublifier after it retrieves the entire listing of chapters from Novelupdates for _any_ novel, I want to **only select a specific range of chapters** to parse and generate as an epub. But while clicking the "**TICK**" box to **select specific chapters**, the extension would suddenly **automatically deselect ALL chapters** that I've previously selected after only eight or so chapters are selected (this number is just a variable as this frequently occurs whenever specific chapters are selected only). So then I have to go back to re-select the same chapters, but it will still continue to de-select the chapters that were specificially selected... Is there a way to perhaps cirumvent this so the selected chapters remain selected?

Also it seems that a **range of chapters** cannot be selected because **CTRL + SHIFT** doesn't work? I'm not too sure if this is a bug, or something else though.

And thank you very much for this wonderful program! :)

---

**Required info (please complete the following information):**
 - Url: Any novelupdates link, but I'll give a random novel link --> **https://www.novelupdates.com/series/after-failing-to-influence-the-protagonist/**
 - Browser [e.g. chrome, firefox]: **Chrome**
 - Extension Version [e.g. 2.0.24]: Latest Version --> **2.0.56**

**Comment by maoserr** [comment]
If you click on anything without either CTRL or Shift, then it's assuming single select, so others are deselected. I think this is probably more a confusion with the UI than an actual bug. I know if you click too fast, it won't have time to process, so it'll deselect because the checkbox didn't receive the click. BTW CTR+SHIFT doesn't do anything, CTRL or SHIFT are multi select and range select.

**Comment by maoserr** [comment]
#172 also reports the same issue. Please reference that

**Comment by vanessabluellie** [comment]
Ah, yes I apologise. I edited my bug report but forgot to indicate which other issue I was referring to.

But regarding the issue, when I tried to select a range of chapters, I had only used **SHIFT** and it would not work. Although this is so, I was able to find a workaround for this. If you want to select a range of chapters, it will not select the specified range **IF** you click on the checkboxes. The user has to click on the **three-lines NEXT TO the checkbox** (the feature that allows you to shift the positions of chapters) and then you can actually select a range of chapters :D

Although, about the automatic deselect issue, I'm clueless on that. It does seem to automatically deselect the selected chapters **unless a very certain position of the checkbox** is clicked (I saw it seems to be the very top right corner of the box). If the right point isn't clicked, it is probably thence assuming single select rather than multiple selections.

**Comment by maoserr** [comment]
hmm, that is also a UI thing. Ctrl and Shift only works outside the checkbox. I can see a lot of people are getting confused by the UI behavior. I will simplify how selections work.

**Comment by maoserr** [comment]
fixed in new version.
